// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpVO2ZFLGV6KT-Do23em5ZkJTBtE9mMBc',
    appId: '1:722451045908:web:613298cf01ae2173459101',
    messagingSenderId: '722451045908',
    projectId: 'smart-irrigation-acd3e',
    authDomain: 'smart-irrigation-acd3e.firebaseapp.com',
    storageBucket: 'smart-irrigation-acd3e.firebasestorage.app',
    measurementId: 'G-DDWPK5PBND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHc6pA6rvA6ZyZTjSvTBDzzCd6oHkSVU0',
    appId: '1:722451045908:android:872d6478f0771529459101',
    messagingSenderId: '722451045908',
    projectId: 'smart-irrigation-acd3e',
    storageBucket: 'smart-irrigation-acd3e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7In9cpZmfPE-aerMDgmF98thQPrMBH8o',
    appId: '1:722451045908:ios:e28ed6279b74700a459101',
    messagingSenderId: '722451045908',
    projectId: 'smart-irrigation-acd3e',
    storageBucket: 'smart-irrigation-acd3e.firebasestorage.app',
    iosBundleId: 'com.example.smartIrrigation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7In9cpZmfPE-aerMDgmF98thQPrMBH8o',
    appId: '1:722451045908:ios:e28ed6279b74700a459101',
    messagingSenderId: '722451045908',
    projectId: 'smart-irrigation-acd3e',
    storageBucket: 'smart-irrigation-acd3e.firebasestorage.app',
    iosBundleId: 'com.example.smartIrrigation',
  );
}
